# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
pod 'FBSDKLoginKit'

target 'MyNotepad' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyNotepad

  target 'MyNotepadTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyNotepadUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end


